### ISSUE TITLE
There's no release version for the package

### ISSUE THREAD

**Issue by AndreiIgna** [patrickbussmann/oauth2-apple#1]
Hi,

Wanted to test the package in my project, but couldn't install it because there's no tagged release.
<img width="1248" alt="Screenshot 2019-10-21 at 13 41 35" src="https://user-images.githubusercontent.com/263021/67202360-c0054f80-f408-11e9-880b-8ab34a1af5f7.png">

Cloud you add a release here please? https://github.com/patrickbussmann/oauth2-apple/releases

**Comment by patrickbussmann** [comment]
It's done @AndreiIgna 👍
