### ISSUE TITLE
Leeway

### ISSUE THREAD

**Issue by lukequinnell** [patrickbussmann/oauth2-apple#18]
Firstly, thank you for your efforts here, its appreciated!

Does your library allow for use of the `JWT::$leeway` configuration?

"You can add a leeway to account for when there is a clock skew times between
the signing and verifying servers. It is recommended that this leeway should
not be bigger than a few minutes."
Source: http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#nbfDef

JWT::$leeway = 60; // $leeway in seconds
$decoded = JWT::decode($jwt, $key, array('HS256'))

**Comment by patrickbussmann** [comment]
I added it to the README.
Its supported because `Firebase\JWT\JWT::$leeway` is `public static` so it can be modified.

Thanks for information.
