### ISSUE TITLE
Problem getting the first and last name

### ISSUE THREAD

**Issue by emunozhern** [patrickbussmann/oauth2-apple#22]
I am calling getResourceOwner($ token); as indicated by the repo, but this returns me null, for the first_name and last_name.

The Repo indicates that by default it brings name and email.
I also tried adding it to the scope, but it doesn't work for me either.

This does not return. 

= ( Help!

**Comment by patrickbussmann** [comment]
Did you tried to go to appleid.apple.com and delete your app from the used apps list.
Then register as a new user to your app.
You should see your name details on $_POST / $_GET (Query params or Body) and then you can call ->getFirstName() / ->getLastName(). - when you requested the scope.

**It's bad but from Apple:** You'll get the name only once at first registration.

**Comment by emunozhern** [comment]
Thank you very much you can get it through $ _POST

I tried with getLastName () but it returned null. An example of how to obtain it in this way would be helpful.

**Comment by patrickbussmann** [comment]
You must ensure that the application is `deleted` on appleid.apple.com!
So when your application name is "Example app" then it shouldnt be in the Application list on appleid.apple.com.

Then register by requesting the scope.
https://github.com/patrickbussmann/oauth2-apple#managing-scopes

```
$options = [
    'scope' => ['name', 'email']
];

$authorizationUrl = $provider->getAuthorizationUrl($options);
```

And then simply...

    printf('Hello %s %s!', $user->getFirstName(), $user->getLastName());
