### ISSUE TITLE
Error while decoding JWK

### ISSUE THREAD

**Issue by breizh81** [patrickbussmann/oauth2-apple#30]
Hello everyone.
I have an error while JWK::decode is called in **AppleAccessToken.php**. The error is `_$keyOrKeyArray must be a string key, an array of string keys,'an instance of Firebase\JWT\Key key or an array of Firebase\JWT\Key keys_`

If in AppleAccessToken.php I change the line 48 from
`$decoded = JWT::decode($options['id_token'], $key, ['RS256']);`
to:
`$decoded = JWT::decode($options['id_token'], new Key($key,'RS256'));`
Everything works. 
In my case  the $keyOrKeyArray is an `OpenSSL key resource @` and with the actual code generates an error. 

Does anyone else had a similar problem?

**Comment by patrickbussmann** [comment]
Perfect 👌

**Comment by hyptos** [comment]
thanks for your work :)
