### ISSUE TITLE
Trail Apple Account 

### ISSUE THREAD

**Issue by basheerv** [patrickbussmann/oauth2-apple#36]
Hi there,
Can anyone tell me, I am using free apple developer account apple OAuth account in but it's give error with client_id?
Anyone to help for this task i will be very thankful of anyone

**Comment by patrickbussmann** [comment]
You need to take care about the setup on the apple side.
A small mistake / typo / whatever can make the whole fail.

Can you give us some example codes?
Or something we can work with?

What is your client id?

If you not want to share it with everyone you can send me a mail and I will only publish the solution here. (no private details)
