### ISSUE TITLE
Function to revoke access_token

### ISSUE THREAD

**Issue by aanders77** [patrickbussmann/oauth2-apple#37]
Starting June 30, 2022, Apple requires that users can delete their accounts in an easy way. One recommendation is that the user's access token is revoked as part of the deletion process. 
Source: [https://developer.apple.com/support/offering-account-deletion-in-your-app](https://developer.apple.com/support/offering-account-deletion-in-your-app)
Documentation: [https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens](https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens)

Can you please add a method to revoke tokens? I tried doing it using php JWT library, but I think it doesn't support ES256 properly.

**Comment by patrickbussmann** [comment]
Hi @aanders77,

please see this example of how to use the new revoke method -> https://github.com/patrickbussmann/oauth2-apple#revoke-code-flow

Thanks for reporting.
