### ISSUE TITLE
String passed to JWK::parseKeySet() expecting array.

### ISSUE THREAD

**Issue by samhibberd** [patrickbussmann/oauth2-apple#5]
Getting an issue with the keys being passed to `JWK::parseKeySet`.

https://github.com/patrickbussmann/oauth2-apple/blob/134ec39429dc90487f7a7f8bfe027192c065eee1/src/Token/AppleAccessToken.php#L85

As it returns JSON think it needs to be decoded to an array:
```
return JWK::parseKeySet(json_decode(file_get_contents('https://appleid.apple.com/auth/keys'), true));
```

**Comment by adrianbardan** [comment]
This seems to happen when using other libraries that depend on firebase/php-jwt, which uses the same namespace as fproject/php-jwt (Firebase\JWT). 

I've proposed a fix in the pull request above.
