### ISSUE TITLE
$payload never return user email

### ISSUE THREAD

**Issue by igomez1993** [patrickbussmann/oauth2-apple#8]
Hi, this photo is a debugg on AppleAccessToken.php after line 57. **

As you can see, $payload never return me: **$payload['email_verified']**, **$payload['email'];**, **$payload['is_private_email']** 

![appleDatosPrivados](https://user-images.githubusercontent.com/66120968/83256719-3c3bee80-a1b3-11ea-8bc4-31d22734d3c8.jpg)

I need it and dont know how to solve this problem.
Thanks

** To get this, i resolved the getApplekey() return problem with json_decode

**Comment by patrickbussmann** [comment]
Parameters like username, email, email verified, is private email and this things are only send with the very first request.
So please delete the application from your apple account first to try it.
When you log in a second time using Sign in with Apple it will not have this details.
https://appleid.apple.com/

Can you check that please?
